ecomstore/ecomstore/cart/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ecomstore.cart.views',
    (r'^$', 'show_cart', {'template_name':'cart/cart.html'}, 'show_cart'),
)

ecomstore/ecomstore/catalog/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ecomstore.catalog.views',
    (r'^$','index', {'template_name': 'catalog/index.html'}, 'catalog_home'),
    (r'^category/(?P<category_slug>[-\w]+)/$', 'show_category', 
       {'template_name': 'catalog/category.html'}, 'catalog_category'),
    (r'^product/(?P<product_slug>[-\w]+)/$', 'show_product', 
       {'template_name': 'catalog/product.html'}, 'catalog_product'),
    (r'^tag_cloud/$', 'tag_cloud', 
       {'template_name': 'catalog/tag_cloud.html'}, 'tag_cloud'),
    (r'^tag/(?P<tag>[-\w]+)/$', 'tag', 
       {'template_name': 'catalog/tag.html'}, 'tag'),
    (r'^review/product/add/$', 'add_review', {}, 'add_product_review'),
    (r'^tag/product/add/$', 'add_tag'),
)

ecomstore/ecomstore/ecomstore/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.defaults import *
from ecomstore import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

admin.autodiscover()


import os

urlpatterns = patterns('',
    # Example:
    # (r'^ecomstore/', include('ecomstore.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^', include('ecomstore.catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
    (r'^billing/', include('billing.urls')),
    (r'^', include('marketing.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            { 'document_root' : os.path.join(settings.CURRENT_PATH, 'static') }),
)

handler404 = 'ecomstore.views.file_not_found_404'
#handler500 = 'ecomstore.views.server_error_500'

ecomstore/ecomstore/catalog/models.py
from django.db import models
from django.http import Http404
from ecomstore import settings
from django.contrib.auth.models import User
import tagging

from django.db.models.signals import post_save, post_delete
from ecomstore.caching.caching import cache_update, cache_evict

class ActiveCategoryManager(models.Manager):
    """ Manager class to return only those categories where each instance is active """
    def get_query_set(self):
        return super(ActiveCategoryManager, self).get_query_set().filter(is_active=True)

class Category(models.Model):
    """ model class containing information about a category in the product catalog """
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True,
                            help_text='Unique value for product page URL, created automatically from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField(max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for keywords meta tag')
    meta_description = models.CharField(max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    active = ActiveCategoryManager()

    class Meta:
        db_table = 'categories'
        ordering = ['name']
        verbose_name_plural = 'Categories'
        
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('catalog_category', (), { 'category_slug': self.slug })
    
    @property
    def cache_key(self):
        return self.get_absolute_url()
    

class ActiveProductManager(models.Manager):
    """ Manager class to return only those products where each instance is active """
    def get_query_set(self):
        return super(ActiveProductManager, self).get_query_set().filter(is_active=True)
    
class FeaturedProductManager(models.Manager):
    """ Manager class to return only those products where each instance is featured """
    def get_query_set(self):
        return super(FeaturedProductManager, self).get_query_set().filter(is_active=True).filter(is_featured=True)

class Product(models.Model):
    """ model class containing information about a product; instances of this class are what the user
    adds to their shopping cart and can subsequently purchase
    
    """
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for product page URL, created automatically from name.')
    brand = models.CharField(max_length=50) 
    sku = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    old_price = models.DecimalField(max_digits=9,decimal_places=2,
                                    blank=True,default=0.00)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    quantity = models.IntegerField()
    description = models.TextField()
    meta_keywords = models.CharField("Meta Keywords",max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for keywords meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    
    # image fields, added in Chapter 7
    # image fields require a varchar(100) in db
    image = models.ImageField(upload_to='images/products/main')
    thumbnail = models.ImageField(upload_to='images/products/thumbnails')
    image_caption = models.CharField(max_length=200)
    
    objects = models.Manager()
    active = ActiveProductManager()
    featured = FeaturedProductManager()
    
    class Meta:
        db_table = 'products'
        ordering = ['-created_at']
    
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('catalog_product', (), { 'product_slug': self.slug })
    
    @property
    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None
    
    def cross_sells(self):
        """ gets other Product instances that have been combined with the current instance in past orders. Includes the orders
        that have been placed by anonymous users that haven't registered
        """
        from ecomstore.checkout.models import Order, OrderItem
        orders = Order.objects.filter(orderitem__product=self)
        order_items = OrderItem.objects.filter(order__in=orders).exclude(product=self)
        products = Product.active.filter(orderitem__in=order_items).distinct()
        return products
    
    # users who purchased this product also bought....
    def cross_sells_user(self):
        """ gets other Product instances that have been ordered by other registered customers who also ordered the current
        instance. Uses all past orders of each registered customer and not just the order in which the current 
        instance was purchased
        
        """
        from ecomstore.checkout.models import Order, OrderItem
        from django.contrib.auth.models import User
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter(order__user__in=users).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products
    
    def cross_sells_hybrid(self):
        """ gets other Product instances that have been both been combined with the current instance in orders placed by 
        unregistered customers, and all products that have ever been ordered by registered customers
        
        """
        from ecomstore.checkout.models import Order, OrderItem
        from django.db.models import Q
        orders = Order.objects.filter(orderitem__product=self)
        users = User.objects.filter(order__orderitem__product=self)
        items = OrderItem.objects.filter( Q(order__in=orders) | 
                      Q(order__user__in=users) 
                      ).exclude(product=self)
        products = Product.active.filter(orderitem__in=items).distinct()
        return products
    
    @property
    def cache_key(self):
        return self.get_absolute_url()
try:
    tagging.register(Product)
except tagging.AlreadyRegistered:
    pass
    
class ActiveProductReviewManager(models.Manager):
    """ Manager class to return only those product reviews where each instance is approved """
    def all(self):
        return super(ActiveProductReviewManager, self).all().filter(is_approved=True)
        
class ProductReview(models.Model):
    """ model class containing product review data associated with a product instance """
    RATINGS = ((5,5),(4,4),(3,3),(2,2),(1,1),)
    
    product = models.ForeignKey(Product)
    user = models.ForeignKey(User)
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(default=5, choices=RATINGS)
    is_approved = models.BooleanField(default=True)
    content = models.TextField()
    
    objects = models.Manager()
    approved = ActiveProductReviewManager()
    
# attach signals to Product and Category model classes 
# to update cache data on save and delete operations
post_save.connect(cache_update, sender=Product)
post_delete.connect(cache_evict, sender=Product) 
post_save.connect(cache_update, sender=Category)
post_delete.connect(cache_evict, sender=Category)

ecomstore/ecomstore/catalog/views.py
from django.shortcuts import get_object_or_404, render_to_response
from ecomstore.catalog.models import Category, Product, ProductReview
from ecomstore.catalog.forms import ProductAddToCartForm, ProductReviewForm
from django.template import RequestContext

from django.core import urlresolvers
from ecomstore.cart import cart
from django.http import HttpResponseRedirect, HttpResponse

from ecomstore.stats import stats
from ecomstore.settings import PRODUCTS_PER_ROW

from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils import simplejson

import tagging
from tagging.models import Tag, TaggedItem

from django.core.cache import cache
from ecomstore.settings import CACHE_TIMEOUT

def index(request, template_name="catalog/index.html"):
    """ site home page """
    search_recs = stats.recommended_from_search(request)
    featured = Product.featured.all()[0:PRODUCTS_PER_ROW]
    recently_viewed = stats.get_recently_viewed(request)
    view_recs = stats.recommended_from_views(request)
    page_title = 'Modern Musician | Musical Instruments and Sheet Music for Musicians'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def show_category(request, category_slug, template_name="catalog/category.html"):
    """ view for each individual category page """
    category_cache_key = request.path
    c = cache.get(category_cache_key)
    if not c:
        c = get_object_or_404(Category.active, slug=category_slug)
        cache.set(category_cache_key, c, CACHE_TIMEOUT)
    products = c.product_set.filter(is_active=True)
    page_title = c.name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description
    
    from django.db import connection
    queries = connection.queries
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def show_product(request, product_slug, template_name="catalog/product.html"):
    """ view for each product page """
    product_cache_key = request.path
    # try to get product from cache
    p = cache.get(product_cache_key)
    # if a cache miss, fall back on db query
    if not p:
        p = get_object_or_404(Product.active, slug=product_slug)
        # store item in cache for next time
        cache.set(product_cache_key, p, CACHE_TIMEOUT)
    categories = p.categories.filter(is_active=True)
    page_title = p.name
    meta_keywords = p.meta_keywords
    meta_description = p.meta_description
    # evaluate the HTTP method, change as needed
    if request.method == 'POST':
        #create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart page
            cart.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = urlresolvers.reverse('show_cart')
            return HttpResponseRedirect(url)
    else:
        #create the unbound form. Notice the request as a keyword argument
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set test cookie to make sure cookies are enabled
    request.session.set_test_cookie()
    stats.log_product_view(request, p)
    # product review additions, CH 10
    product_reviews = ProductReview.approved.filter(product=p).order_by('-date')
    review_form = ProductReviewForm()
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def tag_cloud(request, template_name="catalog/tag_cloud.html"):
    """ view containing a list of tags for active products, sized proportionately by relative
    frequency 
    """
    product_tags = Tag.objects.cloud_for_model(Product, steps=9, 
                                               distribution=tagging.utils.LOGARITHMIC,
                                               filters={'is_active': True })
    page_title = 'Product Tag Cloud'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def tag(request, tag, template_name="catalog/tag.html"):
    """ view listing products that have been tagged with a given tag """
    products = TaggedItem.objects.get_by_model(Product.active, tag)
    page_title = 'Products tagged with ' + tag
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

    
@login_required
def add_review(request):
    """ AJAX view that takes a form POST from a user submitting a new product review;
    requires a valid product slug and args from an instance of ProductReviewForm;
    return a JSON response containing two variables: 'review', which contains 
    the rendered template of the product review to update the product page, 
    and 'success', a True/False value indicating if the save was successful.
    """
    form = ProductReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        slug = request.POST.get('slug')
        product = Product.active.get(slug=slug)
        review.user = request.user
        review.product = product
        review.save()
    
        template = "catalog/product_review.html"
        html = render_to_string(template, {'review': review })
        response = simplejson.dumps({'success':'True', 'html': html})
        
    else:
        html = form.errors.as_ul()
        response = simplejson.dumps({'success':'False', 'html': html})
    return HttpResponse(response, 
                        content_type='application/javascript; charset=utf-8')

@login_required
def add_tag(request):
    """ AJAX view that takes a form POST containing variables for a new product tag;
    requires a valid product slug and comma-delimited tag list; returns a JSON response 
    containing two variables: 'success', indicating the status of save operation, and 'tag',
    which contains rendered HTML of all product pages for updating the product page.
    """
    tags = request.POST.get('tag','')
    slug = request.POST.get('slug','')
    if len(tags) > 2:
        p = Product.active.get(slug=slug)
        html = u''
        template = "catalog/tag_link.html"
        for tag in tags.split():
            tag.strip(',')
            Tag.objects.add_tag(p,tag)
        for tag in p.tags:
            html += render_to_string(template, {'tag': tag })
        response = simplejson.dumps({'success':'True', 'html': html })
    else:
        response = simplejson.dumps({'success':'False'})
    return HttpResponse(response,
                        content_type='application/javascript; charset=utf-8')

ecomstore/ecomstore/templates/catalog/category.html
{% extends "catalog.html" %}

{% block content %}
<h1>{{ c.name }}</h1>
{{ c.description }}
<br /><br />
	{% for p in products %}
	<!-- div class="product_thumbnail">
		<a href="{{ p.get_absolute_url }}">
		<img src="{{ MEDIA_URL }}images/products/thumbnails/{{ p.image }}" alt="{{ p.name }}" class="bn" />
		<br />
		{{ p.name }}
		</a>
	</div -->
	{% include 'tags/product_thumbnail.html' %}
	{% endfor %}
{% endblock %}

ecomstore/ecomstore/templates/catalog/index.html
{% extends "catalog.html" %}

{% load catalog_tags %}

{% block content %}
<h1>Welcome to Modern Musician!</h1>

{% product_list recently_viewed 'Your Recently Viewed' %}
{% product_list view_recs 'Similar Products' %}
{% product_list featured 'Featured Products' %}
{% product_list search_recs 'Recommended For You' %}

{% endblock %}

ecomstore/ecomstore/templates/catalog/product.html
{% extends "catalog.html" %}

{% load catalog_filters %}

{% block content %}
<div xmlns:v="http://rdf.data-vocabulary.org/#" about="{{ p.get_absolute_url }}" typeof="v:Product">
	<div class="product_image" >
		<img src="{{ p.image.url }}" alt="{{ p.name }}" />
		<br />
		{{ p.image_caption }}
	</div>
	<h1><span property="v:name">{{ p.name }}</span></h1>
	Brand: <em><span property="v:brand">{{ p.brand }}<span></em>
	<br /><br />
	SKU: {{ p.sku }}
	<br />
	In categor{{ categories.count|pluralize:"y,ies" }}: 
	{% for c in categories %}
		<a href="{{ c.get_absolute_url }}">
		<span property="v:category">
		{{ c.name }}
		</span>
		</a>
		{% if not forloop.last %}, {% endif %}
	{% endfor %}
	<br /><br />
	{% if p.sale_price %}
		Was: <del>{{ p.old_price|currency }}</del>
		<br />
		Now: <span property="v:price">{{ p.price|currency }}</span>
	{% else %}
		Price: <span property="v:price">{{ p.price|currency }}</span>
	{% endif %}
	<br /><br />
	<form method="post" action="." class="cart">
		{{ form.as_p }}
		<br />
		<input type="submit" value="Add To Cart" name="submit" alt="Add To Cart" />
	</form>
	<div class="cb"><br /><br /></div>
	<h3>Related Products</h3>
		{% for p in p.cross_sells_hybrid %}
			{% include 'tags/product_thumbnail.html' %}
		{% empty %}
			No related products.
		{% endfor %}
	<div class="cb"><br /><br /></div>
	<h3>Product Description</h3>
	<span property="v:description">{{ p.description }}</span>
	
</div>


	<div class="cb"><br /><br /></div>
	<h3>Product Tags</h3>
	 	
	 	<div id="tags">
	 		{% for tag in p.tags %}
	 			{% include 'catalog/tag_link.html' %}
	 		{% endfor %}
	 	</div>
	 	<br />
	 	{% if request.user.is_authenticated %}
	 		<label for="id_tag">Tag this product (must be at least three characters):</label>
	 		<br />
	 		<input id="id_tag" type="text" />
	 		<input type="submit" value="Tag It" id="add_tag" />
	 		
	 	{% else %}
	 		<a href="{% url login %}?next={{ request.path }}">
				Log in to tag this product.
			</a>
	 	{% endif %}
	<div class="cb"><br /><br /></div>
	<h3>Product Reviews</h3>
		{% if request.user.is_authenticated %}
		<a id="add_review">Write a Review</a>
	<div id="review_form">
		<div id="review_errors"></div>
		<table>
		{{ review_form.as_table }}
		<tr><td colspan="2">
			<input type="hidden" id="id_slug" value="{{ p.slug }}" />
			<input type="submit" id="submit_review" value="Submit" />
			<input type="submit" id="cancel_review" value="Cancel" />
		</td></tr>
		</table>
	</div>
		{% else %}
			<a href="{% url login %}?next={{ request.path }}">
				Log in to write your own review.
			</a>
		{% endif %}
		
	<div class="cb"><br /><br /></div>
	
	<div id="reviews">
		{% for review in product_reviews %}
			{% include 'catalog/product_review.html' %}
		{% empty %}
			<div id="no_reviews">
				No product reviews yet.
			</div>
		{% endfor %}
	</div>
	<div class="cb"><br /><br /></div>
{% endblock %}

ecomstore/ecomstore/templates/catalog/product_review.html
<div class="review">
	Rating: {{ review.rating }}
	<strong>{{ review.title }}</strong>
	by {{ review.user.username }}
	<br />
	{{ review.content }}
	<br /><br />
	<hr />
</div>

ecomstore/ecomstore/templates/catalog/tag.html
{% extends "catalog.html" %}

{% block content %}
	<h1>Products tagged with: '{{ tag }}'</h1>
	{% for p in products %}
		{% include 'tags/product_thumbnail.html' %}
	{% endfor %}
{% endblock %}

ecomstore/ecomstore/templates/catalog/tag_cloud.html
{% extends "catalog.html" %}

{% load tagging_tags %}

{% block content %}
	<h1>Product Tag Cloud</h1>
	{% for tag in product_tags %}
		<a href="/tag/{{ tag.name }}/" style="font-size: {{ tag.font_size|add:"11" }}px;">{{ tag.name|slugify }}</a>&nbsp;
	{% endfor %}
{% endblock %}

ecomstore/ecomstore/templates/catalog/tag_link.html
<a href="/tag/{{ tag.name }}/">{{ tag.name|slugify }}</a>&nbsp;