monolith_alt/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/$', views.cart_add, name='cart_add_quick'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

monolith_alt/monolith/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

from shop import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^products/', include('shop.urls', namespace='shop')),
	url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
	url(r'^login/', auth.login, {'template_name': 'users/login.html'}, name="login"),
	url(r'^$', views.dashboard, name='dashboard'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monolith_alt/monolith_alt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

from shop import views

from rest_framework import routers
from rest_export.views import CategoryViewSet, SupplierViewSet, UnitMeasureViewSet, ProductViewSet
from rest_export.views import ProfileViewSet, CustomerViewSet, OrderViewSet, OrderItemViewSet, UserViewSet, GroupViewSet

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'suppliers', SupplierViewSet)
router.register(r'unitmeasures', UnitMeasureViewSet)
router.register(r'products', ProductViewSet)
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'customers', CustomerViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'orderitems', OrderItemViewSet)

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^products/', include('shop.urls', namespace='shop')),
	url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
	url(r'^login/', auth.login, {'template_name': 'users/login.html'}, name="login"),
	url(r'^$', views.dashboard, name='dashboard'),
    url(r'^restf/get/', include(router.urls)), 
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monolith_alt/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^get_supplier_products/(?P<pk>\d+)/$',	views.get_supplier_products, name='get_supplier_products'),
	url(r'^get-products/(?P<supplier_id>\d+)/$',	views.get_products, name='get-products'),
	url(r'^product-autocomplete/$',	views.ProductAutocomplete.as_view(), name='product-autocomplete'),
	url(r'^supplier-autocomplete/$', views.SupplierAutocomplete.as_view(), name='supplier-autocomplete'),
	url(r'^products/import/$', views.product_import, name='product_import'),
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<criteria_slug>[-\w]+)/$', views.product_list, name='product_list_by_criteria'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

monolith_alt/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from users.models import Profile
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)
	
	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_criteria', args=[self.slug])

class Supplier(models.Model):
	user = models.ForeignKey(User, blank=True, null=True)
	name = models.CharField(max_length=100, db_index=True)
	address = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)
	
	class Meta:
		ordering = ('name', 'address',)
		verbose_name = 'supplier'
		verbose_name_plural = 'suppliers'
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_criteria', args=[self.slug])

class UnitMeasure(models.Model):
	name = models.CharField(max_length=100, db_index=True)
	
	def __str__(self):
		return self.name
	
class Product(models.Model):
	category = models.ForeignKey(Category, related_name='products')
	supplier = models.ForeignKey(Supplier, related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

monolith_alt/shop/forms.py
#gui/forms.py

monolith_alt/shop/views.py
#gui/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.core import serializers
from dal import autocomplete
from tablib import Dataset
from slugify import slugify

from cart.forms import CartAddProductForm
from cart.cart import Cart
from orders.forms import OrderCreateForm
from orders.views import get_orders_of_user, chart_ordered_products, get_chart_ordered_amounts
from users.views import get_favorite_products

from .models import Category, Product, Supplier
from .resources import ProductResource
from users.models import Customer
from orders.models import SupplierOrder

def product_list(request, criteria_slug=None):
	category = None
	products = Product.objects.filter(available=True)
	
	if criteria_slug:
		try:
			category = Category.objects.get(slug=criteria_slug)
			products = products.filter(category=category)
			return render(request, 'shop/product/list.html', {'category': category,'products': products})
		except Category.DoesNotExist:
			pass

		try:
			supplier = Supplier.objects.get(slug=criteria_slug)
			products = products.filter(supplier=supplier)
			return render(request, 'shop/product/list.html', {'supplier': supplier, 'products': products})
		except Supplier.DoesNotExist:
			pass
			
	return render(request, 'shop/product/list.html', {'category': category, 'products': products})

def product_detail(request, id, slug):

	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()

	return render(request, 'shop/product/detail.html', {'product': product,'cart_product_form': cart_product_form})

@login_required()
def dashboard(request):
	orders = get_orders_of_user(request.user)
	# favorites = get_favorite_products(request.user)
	# chart_qty = chart_ordered_products(request.user)
	# chart_amount = get_chart_ordered_amounts(request.user)
	# return render(request, 'shop/dashboard.html', {'orders': orders, 'products':favorites, 'chart_qty':chart_qty, 'chart_amount':chart_amount})
	cart = Cart(request)
	for item in cart:
		print(item)
		item['update_form'] = CartAddProductForm(initial={'product_name': item['product'].id, 'quantity': item['quantity'], 'um': item['um'], 'update': True})

	quick_submit_form = OrderCreateForm()
	
	custID = int(request.session.get("customer_selected", '0'))
	if custID > 0:
		cust = get_object_or_404(Customer, id=custID)
		quick_submit_form.initial['customer'] = custID
		quick_submit_form.initial['first_name'] = cust.first_name
		quick_submit_form.initial['last_name'] = cust.last_name
		quick_submit_form.initial['email'] = cust.email
		quick_submit_form.initial['address'] = cust.address
		quick_submit_form.initial['phone'] = cust.phone
	
	# quick_submit_form.initial['first_name'] = request.user.first_name
	# quick_submit_form.initial['last_name'] = request.user.last_name
	# quick_submit_form.initial['email'] = request.user.email
	# if request.user.profile:
	# 	quick_submit_form.initial['address'] = request.user.profile.address
	# 	quick_submit_form.initial['phone'] = request.user.profile.phone

	return render(request, 'shop/dashboard.html', {'orders': orders, 'search_form': CartAddProductForm, 'cart': cart, 'quick_submit_form':quick_submit_form})#, {'orders': orders, 'products':favorites, 'chart_qty':chart_qty, 'chart_amount':chart_amount})

def get_supplier_products(self, pk):
	products = Product.objects.filter(supplier_id=pk)
	return HttpResponse(serializers.serialize('json',products), content_type="application/json")

def get_products(self, supplier_id):
	products = Product.objects.filter(supplier=supplier_id)
	return HttpResponse(serializers.serialize('json',products), content_type="application/json")


def product_import(request):
	context = {}
	if request.method == 'POST':
		product_resource = ProductResource()
		dataset = Dataset()
		new_products_file = request.FILES['products_file']
		string_file = new_products_file.read().decode()
		page_result={}
		items = []
		try:
			imported_data = dataset.load(string_file, format='csv')
			# result = product_resource.import_data(dataset, dry_run=True)  # Test the data import
			# if not result.has_errors():
			page_result['message']="Success! The following items were imported:"
			for row in dataset.dict:
				product = Product()
				product.category = Category.objects.get(id=row['category'])
				product.supplier = Supplier.objects.get(id=row['supplier'])
				product.name = row['name']
				product.slug = slugify(row['name'])
				product.description = row['description']
				product.price = row['price']
				product.stock = row['stock']
				
				product.save()
				items.append(product)
		except Exception:
			page_result['error']="Error while importing items!"

			# product_resource.import_data(dataset, dry_run=False)  # Actually import now
		# else:
		# 	page_result['message']="Error while importing items"

		if items: page_result['items'] = items
		context['result'] = page_result
	return render(request, 'shop/product/import.html', context)




class ProductAutocomplete(autocomplete.Select2QuerySetView):
	def get_queryset(self):
		if not self.request.user.is_authenticated():
			return Product.objects.none()

		qs = Product.objects.all()

		if self.q:
			qs = qs.filter(name__istartswith=self.q)

		return qs


class SupplierAutocomplete(autocomplete.Select2QuerySetView):
	def get_queryset(self):
		if not self.request.user.is_authenticated():
			return Supplier.objects.none()

		qs = Supplier.objects.all()

		if self.q:
			qs = qs.filter(name__istartswith=self.q)

		return qs
	
def mySupplierOrders(request):
	objs = SupplierOrder.objects.filter(user=request.user)
	return render(request, 'shop/sheet.html', {'objs': objs})

monolith_alt/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
	{% if product %}
    	{{ product.name }}
	{% endif %}
{% endblock %}

{% block content %}

<section>
	<div class="section-body contain-lg">
	    <div class="row">
	        <div class="col-lg-12">
				<div class="card card-underline">
					<div class="card-head">
						<header>{% if product %}
									{{ product.name }}
								{% endif %}
						</header>
					</div>
					<!-- page header end -->
					<div class="card-body">
						<img class="img-responsive" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
						<h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
						<h2>${{ product.price }}</h2>
						<form action="{% url "cart:cart_add" product.id %}" method="post" class="form">
								{{ cart_product_form }}
								{% csrf_token %}
								<button type="submit" class="btn btn-sm btn-danger">
								  <i class="fa fa-cart-plus fa-2x"></i>
								</button>
						</form>	
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

monolith_alt/templates/shop/product/import.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Import{% endblock %}

{% block content %}
<section>
	<div class="section-body contain-lg">
		<div class="row">
			<div class="col-lg-12">
				<div class="card card-underline">
					<div class="card-head">
						<header>Import a product list</header>
					</div>
					<div class="card-body">
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<row>
							<label class="btn btn-primary" for="my-file-selector">
								<input id="my-file-selector" name="products_file" type="file" style="display:none" 
								onchange="$('#upload-file-info').html(this.files[0].name)">Browse</label>
							<button type="submit" class="btn btn-default">Import</button>
							<span class='label label-warning' id="upload-file-info"></span>
							</row>
						  </form>
					</div>
				</div>
			</div>
			{% if result %}
				{% if result.error %}
					<div class="col-lg-12">
						<div class="card card-underline">
							<div class="card-head">
								<header>{{ result.error }}</header>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<div class="col-lg-12">
						<div class="card card-underline">
							<div class="card-head">
								<header>{{ result.message }}</header>
							</div>
							<div class="card-body">
								<table class="table">
									<thead>
										<tr>
											<th>Id</th>
											<th>Category</th>
											<th>Product name</th>
											<th>Product description</th>
											<th>Supplier</th>
											<th>Price</th>
											<th>Stock</th>
										</tr>
									</thead>
										{% for product in result.items %}
											<tr>
												<td>{{ product.id }}</td>
												<td>{{ product.category.name }}</td>
												<td>{{ product.name }}</td>
												<td>{{ product.description }}</td>
												<td>{{ product.supplier.name }}</td>
												<td>{{ product.price }}</td>
												<td>{{ product.stock }}</td>
											</tr>
										{% endfor %}
								</table>
							</div>
						</div>
					</div>
				</div>
			{% endif %}
		{% endif %}
	</div>
</section>
{% endblock %}

monolith_alt/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{% if category %}
					{{ category.name }}
				{% elif supplier %}
					{{ supplier.name }}
				{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<section>
	<div class="section-body contain-lg">
	    <div class="row">
	        <div class="col-lg-12">
				<div class="card card-underline">
					<div class="card-head">
						<header>{% if category %}
									{{ category.name }}
								{% elif supplier %}
									{{ supplier.name }}
								{% else %}Products{% endif %}
						</header>
					</div>
					<!-- page header end -->
					<div class="card-body">
						<div class="row">
							{% for product in products %}
					    		<div class="col-md-3">
					        		<div class="card">
										<div class="card-head">
											<header>{{ product.name }}
												<p>{{ product.price }}$</p>
											</header>
											<div class="tools">
												<form id="add_product" action="{% url "cart:cart_add" product.id %}" method="post">
														{{ cart_product_form }}
														{% csrf_token %}
														<button type="submit" class="btn btn-danger">
														  <i class="fa fa-cart-plus fa-2x"></i>
														</button>
												</form>
											</div>
										</div>
										<div class="card-body text-default-light">
											<a href="{{ product.get_absolute_url }}">
												<img class="img-responsive" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
											</a>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

monolith_alt/templates/shop/product/list_naked.html
{% load staticfiles %}

<div class="contain-lg">
    <div class="row">
        <div class="col-lg-12">
			<div class="card card-underline">
				<div class="card-head">
					<header>Your favorite products
					</header>
				</div>
				<div class="card-body">
					{% if not products %}
						<h1>You have no favorite products, place some orders first!</h1>
					{% else %}
						<div class="row">
							{% for product in products %}
								<div class="col-md-3">
				    				<div class="card">
										<div class="card-head">
											<header>{{ product.name }}<br>{{ product.price }}$
											</header>
											<div class="tools">
												<form id="add_product" action="{% url "cart:cart_add" product.id %}" method="post">
														{{ cart_product_form }}
														{% csrf_token %}
														<button type="submit" class="btn btn-danger">
														  <i class="fa fa-cart-plus fa-2x"></i>
														</button>
												</form>
											</div>
										</div>
										<div class="card-body text-default-light">
											<a href="{{ product.get_absolute_url }}">
												<img class="img-responsive" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
											</a>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

monolith_alt/templates/shop/product/product_autocomplete.html
{% load autocomplete_light_tags %}

{% if choices %}
    <h2>{% trans 'Please select a product' %}</h2>
    {% for choice in choices %}
        {{ choice|autocomplete_light_choice_html:autocomplete }}
    {% endfor %}
{% else %}
    <h2>{% trans 'No matching product found' %}</h2>
{% endif %}