ecomstore/ecomstore/cart/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ecomstore.cart.views',
    (r'^$', 'show_cart', {'template_name':'cart/cart.html'}, 'show_cart'),
)

ecomstore/ecomstore/ecomstore/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.defaults import *
from ecomstore import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

admin.autodiscover()


import os

urlpatterns = patterns('',
    # Example:
    # (r'^ecomstore/', include('ecomstore.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^', include('ecomstore.catalog.urls')),
    (r'^cart/', include('cart.urls')),
    (r'^checkout/', include('checkout.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^search/', include('search.urls')),
    (r'^billing/', include('billing.urls')),
    (r'^', include('marketing.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            { 'document_root' : os.path.join(settings.CURRENT_PATH, 'static') }),
)

handler404 = 'ecomstore.views.file_not_found_404'
#handler500 = 'ecomstore.views.server_error_500'

ecomstore/ecomstore/search/models.py
from django.db import models
from django.contrib.auth.models import User

class SearchTerm(models.Model):
    """ stores the text of each internal search submitted """
    q = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True)
    tracking_id = models.CharField(max_length=50, default='')
    
    def __unicode__(self):
        return self.q

ecomstore/ecomstore/templates/tags/cart_box.html
<a href="{% url show_cart %}">
{% with cart_item_count as count %}
Shopping Cart
<br />
{{ count }} Item{{ count|pluralize }}
{% endwith %}
</a>

ecomstore/ecomstore/templates/tags/category_list.html
{% load cache %}

<h3>Categories</h3>
<ul id="categories">

{% with active_categories as cats %}
	{% for c in cats %}
		<li>
		{% ifequal c.get_absolute_url request_path %}
		{{ c.name }}<br />
		{% else %}
		<a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a><br />
		{% endifequal %}
		</li>
	{% endfor %}
{% endwith %}

</ul>

ecomstore/ecomstore/templates/tags/footer.html
{% load cache %}

{% cache 3600 footer_links %}
<a href="{% url catalog_home %}">Home</a>
	{% with flatpage_list as pages %}
		{% for page in pages %}
			<a href="{{ page.url }}">{{ page.title }}</a>
		{% endfor %}
	{% endwith %}
{% endcache %}
<a href="{% url show_cart %}">Shopping Cart</a>
<a href="{% url tag_cloud %}">Tag Cloud</a>

ecomstore/ecomstore/templates/tags/form_table_row.html
<tr>
	<th>
	{% if form_field.field.required %}*{% endif %}
	{{ form_field.label_tag }}
	</th>
	<td>
	{% if form_field.errors %}
		<ul class="errorlist">
		{% for error in form_field.errors %}
			<li>{{ form_field.label }}: {{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
			
	{{ form_field }}
	</td>
</tr>

ecomstore/ecomstore/templates/tags/navigation.html
<ul>
	<li><a href="{% url catalog_home %}">Home</a></li>
	<li><a href="/about/">About</a></li>
	<li><a href="/privacy-policy/">Privacy</a></li>
	<li><a href="/contact/">Contact</a></li>
	
	<li>
		<a href="{% url my_account %}">My Account</a>
	</li>
</ul>
<div class="fr">
<ul>
	<li>
		{% if user.is_authenticated %}
			<a href="{% url django.contrib.auth.views.logout %}">Logout</a>
		{% else %}
			<a href="{% url register %}">Sign Up</a>
			</li>
			<li>
			<a href="{% url django.contrib.auth.views.login %}">Login</a>
		{% endif %}
	</li>
</ul>
</div>
<div class="cb"></div>

ecomstore/ecomstore/templates/tags/pagination_links.html
{% if p.has_other_pages %}
	{% if p.has_previous %}
		<a href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">&laquo; Previous</a>
	{% else %}
		&laquo; Previous
	{% endif %}
	
	| Page {{ p.number }} of {{ paginator.num_pages }} | 
	
	{% if p.has_next %}
		<a href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">Next &raquo;</a>
	{% else %}
		Next &raquo;
	{% endif %}
{% endif %}

ecomstore/ecomstore/templates/tags/product_list.html
{% for p in products %}
	{% if forloop.first %}
		<h3>{{ header_text }}</h3>
	{% endif %}
	{% include 'tags/product_thumbnail.html' %}
	{% if forloop.last %}
		<div class="cb">&nbsp;</div>
	{% endif %}
{% endfor %}

ecomstore/ecomstore/templates/tags/product_thumbnail.html
<div class="product_thumbnail">
	<a href="{{ p.get_absolute_url }}">
		<img src="{{ p.thumbnail.url }}" alt="{{ p.name }}" class="bn" />
		<br />
		{{ p.name }}
	</a>
</div>

ecomstore/ecomstore/templates/tags/search_box.html
<form id="search" action="{% url search_results %}" method="get">
<h3><label for="id_q">Search</label></h3>
	<div style="text-align:right;">
	{{ form.q }}
		<input type="submit" value="Search" />
	</div>
</form>