monolith_alt/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/$', views.cart_add, name='cart_add_quick'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

monolith_alt/monolith/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

from shop import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^products/', include('shop.urls', namespace='shop')),
	url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
	url(r'^login/', auth.login, {'template_name': 'users/login.html'}, name="login"),
	url(r'^$', views.dashboard, name='dashboard'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monolith_alt/monolith_alt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth

from shop import views

from rest_framework import routers
from rest_export.views import CategoryViewSet, SupplierViewSet, UnitMeasureViewSet, ProductViewSet
from rest_export.views import ProfileViewSet, CustomerViewSet, OrderViewSet, OrderItemViewSet, UserViewSet, GroupViewSet

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'suppliers', SupplierViewSet)
router.register(r'unitmeasures', UnitMeasureViewSet)
router.register(r'products', ProductViewSet)
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'customers', CustomerViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'orderitems', OrderItemViewSet)

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^products/', include('shop.urls', namespace='shop')),
	url(r'^portfolios/', include('portfolios.urls', namespace='portfolios')),
	url(r'^login/', auth.login, {'template_name': 'users/login.html'}, name="login"),
	url(r'^$', views.dashboard, name='dashboard'),
    url(r'^restf/get/', include(router.urls)), 
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monolith_alt/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^mysupplierorders/$', views.supplierorder_list, name='supplierorder_list'), 
	url(r'^addmysupplierorder/$', views.supplierorder_new, name='supplierorder_new'),
	url(r'^editmysupplierorder/(?P<pk>\d+)/$', views.supplierorder_edit, name='supplierorder_edit'),
	url(r'^delmysupplierorder/(?P<pk>\d+)/$', views.supplierorder_delete, name='supplierorder_delete'),
	url(r'^$', views.order_list, name='order_list'),
	url(r'^(?P<order_id>\d+)/$', views.order_detail, name='order_detail'), 
	url(r'^create/$', views.order_create, name='order_create'),
	# url(r'^edit/(?P<order_id>\d+)/$', views.order_edit, name='order_edit'),
	url(r'^delete/(?P<order_id>\d+)/$', views.order_delete, name='order_delete'),
	url(r'^export/(?P<customer_id>\d+)/$', views.order_export, name='order_export'),
	url(r'^export/order/(?P<order_id>\d+)/$', views.order_single_export, name='order_single_export'),

]

monolith_alt/portfolios/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^mines/$', views.customer_portfolio_list, name='customer_portfolio_list'), 
	url(r'^addmine/$', views.customer_portfolio_new, name='customer_portfolio_new'),
	url(r'^editmine/(?P<pk>\d+)/$', views.customer_portfolio_edit, name='customer_portfolio_edit'),
	url(r'^delmine/(?P<pk>\d+)/$', views.customer_portfolio_delete, name='customer_portfolio_delete'),
	url(r'^get_portfolio_products/(?P<customer_id>\d+)/(?P<supplier_id>\d+)/$',	views.get_portfolio_products, name='get_portfolio_products'),
	url(r'^list/$', views.portfolio_list, name='portfolio_list'),
	url(r'^add/$', views.portfolio_add, name='portfolio_add'),
	url(r'^order/$', views.portfolio_order, name='portfolio_order'),
	url(r'^(?P<id>\d+)/$', views.portfolio_detail, name='portfolio_detail'),
	url(r'^delete/(?P<portfolio_id>\d+)/$', views.portfolio_delete, name='portfolio_delete'),
]

monolith_alt/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^get_supplier_products/(?P<pk>\d+)/$',	views.get_supplier_products, name='get_supplier_products'),
	url(r'^get-products/(?P<supplier_id>\d+)/$',	views.get_products, name='get-products'),
	url(r'^product-autocomplete/$',	views.ProductAutocomplete.as_view(), name='product-autocomplete'),
	url(r'^supplier-autocomplete/$', views.SupplierAutocomplete.as_view(), name='supplier-autocomplete'),
	url(r'^products/import/$', views.product_import, name='product_import'),
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<criteria_slug>[-\w]+)/$', views.product_list, name='product_list_by_criteria'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

monolith_alt/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth
from . import views

urlpatterns = [
	url(r'^login/$', auth.login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', auth.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^get-customers/(?P<customer_id>\d+)/$',	views.get_customers, name='get-customers'),
  	url(r'^mycustomers/$', views.customer_list, name='customer_list'),
    url(r'^mysuppliers/$', views.supplier_sheet, name='supplier_sheet'),
  	url(r'^customers/$', views.customer_sheet, name='customer_sheet'),
	url(r'^customers/add/$', views.customer_add, name='customer_add'),
	url(r'^customers/(?P<id>\d+)/$', views.customer_detail, name='customer_detail'),
	url(r'^customers/delete/(?P<customer_id>\d+)/$', views.customer_delete, name='customer_delete'),
	url(r'^customers/import/$', views.customer_import, name='customer_import'),
]

monolith_alt/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from users.models import Profile
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)
	
	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_criteria', args=[self.slug])

class Supplier(models.Model):
	user = models.ForeignKey(User, blank=True, null=True)
	name = models.CharField(max_length=100, db_index=True)
	address = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)
	
	class Meta:
		ordering = ('name', 'address',)
		verbose_name = 'supplier'
		verbose_name_plural = 'suppliers'
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_criteria', args=[self.slug])

class UnitMeasure(models.Model):
	name = models.CharField(max_length=100, db_index=True)
	
	def __str__(self):
		return self.name
	
class Product(models.Model):
	category = models.ForeignKey(Category, related_name='products')
	supplier = models.ForeignKey(Supplier, related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

monolith_alt/shop/forms.py
#gui/forms.py

monolith_alt/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Customer

class SignUpForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Input a valid email address.')
	first_name = forms.CharField(max_length=30)
	last_name = forms.CharField(max_length=30)
	address = forms.CharField(max_length=250)
	postal_code = forms.CharField(max_length=20, required=False, help_text='Optional.')
	city = forms.CharField(max_length=100)

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name', 'address', 'postal_code', 'city', 'password1', 'password2', )


class CustomerForm(forms.ModelForm):
	first_name = forms.CharField(max_length=40, label='first_name', widget=forms.TextInput(attrs={'placeholder': 'First name'}))
	last_name = forms.CharField(max_length=40, label='last_name', widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
	address = forms.CharField(max_length=250, label='address', widget=forms.TextInput(attrs={'placeholder': 'Address'}))
	city = forms.CharField(max_length=20, label='city', widget=forms.TextInput(attrs={'placeholder': 'City'}))
	phone = forms.CharField(max_length=20, label='phone', widget=forms.TextInput(attrs={'placeholder': 'Phone'}))
	email = forms.EmailField(max_length=40, help_text='Required. Input a valid email address.', label='email', widget=forms.TextInput(attrs={'placeholder': 'Email'}))

	class Meta:
		model = Customer
		fields = ('first_name', 'last_name', 'address', 'city', 'phone', 'email', )

monolith_alt/shop/views.py
#gui/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.core import serializers
from dal import autocomplete
from tablib import Dataset
from slugify import slugify

from cart.forms import CartAddProductForm
from cart.cart import Cart
from orders.forms import OrderCreateForm
from orders.views import get_orders_of_user, chart_ordered_products, get_chart_ordered_amounts
from users.views import get_favorite_products

from .models import Category, Product, Supplier
from .resources import ProductResource
from users.models import Customer
from orders.models import SupplierOrder

def product_list(request, criteria_slug=None):
	category = None
	products = Product.objects.filter(available=True)
	
	if criteria_slug:
		try:
			category = Category.objects.get(slug=criteria_slug)
			products = products.filter(category=category)
			return render(request, 'shop/product/list.html', {'category': category,'products': products})
		except Category.DoesNotExist:
			pass

		try:
			supplier = Supplier.objects.get(slug=criteria_slug)
			products = products.filter(supplier=supplier)
			return render(request, 'shop/product/list.html', {'supplier': supplier, 'products': products})
		except Supplier.DoesNotExist:
			pass
			
	return render(request, 'shop/product/list.html', {'category': category, 'products': products})

def product_detail(request, id, slug):

	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()

	return render(request, 'shop/product/detail.html', {'product': product,'cart_product_form': cart_product_form})

@login_required()
def dashboard(request):
	orders = get_orders_of_user(request.user)
	# favorites = get_favorite_products(request.user)
	# chart_qty = chart_ordered_products(request.user)
	# chart_amount = get_chart_ordered_amounts(request.user)
	# return render(request, 'shop/dashboard.html', {'orders': orders, 'products':favorites, 'chart_qty':chart_qty, 'chart_amount':chart_amount})
	cart = Cart(request)
	for item in cart:
		print(item)
		item['update_form'] = CartAddProductForm(initial={'product_name': item['product'].id, 'quantity': item['quantity'], 'um': item['um'], 'update': True})

	quick_submit_form = OrderCreateForm()
	
	custID = int(request.session.get("customer_selected", '0'))
	if custID > 0:
		cust = get_object_or_404(Customer, id=custID)
		quick_submit_form.initial['customer'] = custID
		quick_submit_form.initial['first_name'] = cust.first_name
		quick_submit_form.initial['last_name'] = cust.last_name
		quick_submit_form.initial['email'] = cust.email
		quick_submit_form.initial['address'] = cust.address
		quick_submit_form.initial['phone'] = cust.phone
	
	# quick_submit_form.initial['first_name'] = request.user.first_name
	# quick_submit_form.initial['last_name'] = request.user.last_name
	# quick_submit_form.initial['email'] = request.user.email
	# if request.user.profile:
	# 	quick_submit_form.initial['address'] = request.user.profile.address
	# 	quick_submit_form.initial['phone'] = request.user.profile.phone

	return render(request, 'shop/dashboard.html', {'orders': orders, 'search_form': CartAddProductForm, 'cart': cart, 'quick_submit_form':quick_submit_form})#, {'orders': orders, 'products':favorites, 'chart_qty':chart_qty, 'chart_amount':chart_amount})

def get_supplier_products(self, pk):
	products = Product.objects.filter(supplier_id=pk)
	return HttpResponse(serializers.serialize('json',products), content_type="application/json")

def get_products(self, supplier_id):
	products = Product.objects.filter(supplier=supplier_id)
	return HttpResponse(serializers.serialize('json',products), content_type="application/json")


def product_import(request):
	context = {}
	if request.method == 'POST':
		product_resource = ProductResource()
		dataset = Dataset()
		new_products_file = request.FILES['products_file']
		string_file = new_products_file.read().decode()
		page_result={}
		items = []
		try:
			imported_data = dataset.load(string_file, format='csv')
			# result = product_resource.import_data(dataset, dry_run=True)  # Test the data import
			# if not result.has_errors():
			page_result['message']="Success! The following items were imported:"
			for row in dataset.dict:
				product = Product()
				product.category = Category.objects.get(id=row['category'])
				product.supplier = Supplier.objects.get(id=row['supplier'])
				product.name = row['name']
				product.slug = slugify(row['name'])
				product.description = row['description']
				product.price = row['price']
				product.stock = row['stock']
				
				product.save()
				items.append(product)
		except Exception:
			page_result['error']="Error while importing items!"

			# product_resource.import_data(dataset, dry_run=False)  # Actually import now
		# else:
		# 	page_result['message']="Error while importing items"

		if items: page_result['items'] = items
		context['result'] = page_result
	return render(request, 'shop/product/import.html', context)




class ProductAutocomplete(autocomplete.Select2QuerySetView):
	def get_queryset(self):
		if not self.request.user.is_authenticated():
			return Product.objects.none()

		qs = Product.objects.all()

		if self.q:
			qs = qs.filter(name__istartswith=self.q)

		return qs


class SupplierAutocomplete(autocomplete.Select2QuerySetView):
	def get_queryset(self):
		if not self.request.user.is_authenticated():
			return Supplier.objects.none()

		qs = Supplier.objects.all()

		if self.q:
			qs = qs.filter(name__istartswith=self.q)

		return qs
	
def mySupplierOrders(request):
	objs = SupplierOrder.objects.filter(user=request.user)
	return render(request, 'shop/sheet.html', {'objs': objs})

monolith_alt/templates/shop/base.html
{% load staticfiles %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %} | Shop</title>
        <script src="{% static 'js/libs/jquery/jquery-3.2.1.min.js' %}"></script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialadmin.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/jquery.dataTables.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.colVis.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/print.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/libs/multi-select/multi-select.css' %}">
    </head>

    <body class="menubar-pin menubar-hoverable header-fixed">
    
    {% if user.is_authenticated %}
        {% include 'shop/header.html' %}
        {% include 'shop/menubar.html' %}
    {% endif %}


    <div id="base">
        <div class="offcanvas">
        </div>
        <div id="content">
            <div id="message_placeholder">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert {{ message.tags }} text-center alert-dismissable"{% endif %}>
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>

        {% block content %}
        {% endblock %}
    </div>        
        <script src="{% static 'js/libs/bootstrap/bootstrap.js' %}"></script>
        <script src="{% static 'js/libs/jquery-ui/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>
        <script src="{% static 'js/libs/flot/jquery.flot.min.js' %}"></script>
        <script src="{% static 'js/libs/raphael.min.js' %}"></script>
        <script src="{% static 'js/libs/morris.js-0.5.1/morris.min.js' %}"></script>
        
        <!-- DATATABLE -->
        <script src="{% static 'js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
        <script src="{% static 'js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>

        <script src="{% static 'js/core/App.js' %}"></script>
        <script src="{% static 'js/core/AppNavigation.js' %}"></script>
        <script src="{% static 'js/core/AppOffcanvas.js' %}"></script>
        <script src="{% static 'js/core/AppCard.js' %}"></script>
        <script src="{% static 'js/core/AppForm.js' %}"></script>
        <script src="{% static 'js/core/AppVendor.js' %}"></script>
        <script src="{% static 'js/core/Demo.js' %}"></script>
        <script src="{% static 'js/core/DemoTableDynamic.js' %}"></script>
        <script src="{% static 'js/core/DemoCharts.js' %}"></script>

        {% block javascript %}
        {% endblock %}
    </body>
</html>

monolith_alt/templates/shop/dashboard.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<section>
	{% if chart_qty or chart_amount %}
		<div class="section-body contain-lg">
			<div class="row">
				<div class="col-lg-6">
					<div class="card">
						<div class="card-body">
							<div id="qty-chart" class="flot height-6" data-title="Quantity" data-color="#0aa89e"></div>
							<small>Different items ordered</small>
							<!-- <em class="text-caption">Different items ordered</em> -->
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="card">
						<div class="card-body">
							<!-- <div id="amount-chart" class="height-5" data-colors="#9C27B0,#0aa89e"></div> -->
							<div id="amount-chart" class="flot height-6" data-title="Amount" data-color="#9C27B0,#0aa89e"></div>
							<small>Amount spent per order</small>
						</div>
					</div>
				<!-- <em class="text-caption">wasd</em> -->
				</div>
			</div>
		</div>
	<script type="text/javascript">
		$(document).ready(function(){ 

			json_data_qty = {{chart_qty|safe}};
			json_data_amount = {{chart_amount|safe}};

			$.drawFlotChart("#qty-chart", json_data_qty);
			$.drawFlotChart("#amount-chart", json_data_amount);
			// $.drawMorrisAreaChart("#amount-chart", json_data_amount);
		});
	</script> 
	{% endif %}

	{% include 'orders/quick.html' %}
	{% include 'orders/list_naked.html' %}
	{% include 'shop/product/list_naked.html' %}
</section>


{% endblock %}

monolith_alt/templates/shop/header.html
{% load static %}
<header id="header" >
    <div class="headerbar">
        <div class="headerbar-left">
            <ul class="header-nav header-nav-options">
                <li class="header-nav-brand" >
                    <div class="brand-holder">
                        <a href="{% url 'shop:product_list' %}">
                            <span class="text-lg text-light text-danger">Shoop</span><span class="text-lg text-bold text-primary"> in Shop</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="headerbar-right">
            <ul class="header-nav header-nav-options">
                <li class="header-nav">
                    {% with total_items=cart|length %} 
                        {% if cart|length > 0 %} 
                            <a href="{% url 'cart:cart_detail' %}">
                                <span class="profile-info">
                                    <h4 class="text-lg text-bold text-secondary">{{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price|floatformat:"2" }}</h4>
                                </span>
                            </a>
                        {% else %} 
                            <span class="profile-info">
                                <h4 class="text-lg text-bold text-secondary">Your cart is empty</h4>
                            </span>
                        {% endif %} 
                    {% endwith %}
                </li>
            </ul>

            <ul class="header-nav header-nav-profile">
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static "img/no_image.png" %}" alt="" title="" style="">
                        <span class="profile-info">
                            {{ user.get_username }}
                            <small>{% if user.is_staff %}Staff{% else %}Regular user{% endif %}</small>
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Account</li>
                        <li><a href="/admin">Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'users:logout' %}?next=/"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</header>

monolith_alt/templates/shop/menubar.html
{% load static %}
<div id="menubar" class="menubar animate">
    <div class="menubar-scroll-panel">
        <ul id="main-menu" class="gui-controls">
            <li>
                <a href="{% url 'dashboard' %}" >
                    <div class="gui-icon"><i class="md md-home"></i></div>
                    <span class="title">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="{% url 'portfolios:portfolio_list' %}" >
                    <div class="gui-icon"><i class="fa fa-book"></i></div>
                    <span class="title">Product portfolios</span>
                </a>
            </li>

            <li  class="gui-folder expanded">
                <a href="{% url 'orders:supplierorder_list' %}">
                 <div class="gui-icon"><i class="fa fa-book"></i></div>
                 <span class="title">My orders</span>
                </a>
                <ul>
                    <li>
                        <a href="{% url 'users:customer_sheet' %}" >
		                    <div class="gui-icon"><i class="fa fa-user"></i></div>
		                    <span class="title">My Customers</span>
		                </a>
                    </li>
                    <li>
                        <a href="{% url 'users:supplier_sheet' %}">
	                         <div class="gui-icon"><i class="fa fa-truck"></i></div>
	                         <span class="title">My suppliers</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'portfolios:customer_portfolio_list' %}">
	                         <div class="gui-icon"><i class="fa fa-user"></i></div>
	                         <span class="title">My portfolios</span>
                        </a> 
                    </li>
                    <li>
                        <a href="{% url 'orders:supplierorder_new' %}">
                         <div class="gui-icon"><i class="fa fa-book"></i></div>
                         <span class="title">Order a Portfolio</span>
                        </a>
                    </li>
                </ul>
            </li>

           <li class="gui-folder expanded">
                <a>
                    <div class="gui-icon"><i class="fa fa-plus"></i></div>
                    <span class="title">Import</span>
                </a>
                <ul>
                    <li>
                        <a href="{% url 'users:customer_import' %}">Customers</a>
                    </li>
                    <li>
                        <a href="{% url 'shop:product_import' %}">Products</a>
                    </li>
                </ul>
            </li>
            {% load sidebar %}
            {% sidebar_categories as categories%}
            {% sidebar_suppliers as suppliers%}
            <li class="gui-folder expanded">
                <a>
                    <div class="gui-icon"><i class="fa fa-rocket"></i></div>
                    <span class="title">Product categories</span>
                </a>

                <ul>
                    {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="active"{% endif %}>
                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="gui-folder expanded">
                <a>
                    <div class="gui-icon"><i class="fa fa-truck"></i></div>
                    <span class="title">Suppliers</span>
                </a>

                <ul>
                    {% for s in suppliers %}
                        <li {% if supplier.slug == s.slug %}class="active"{% endif %}>
                            <a href="{{ s.get_absolute_url }}">{{ s.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
        <div class="menubar-foot-panel">
            <small class="no-linebreak hidden-folded">
                <span class="opacity-75">alfa</span> <strong>smth</strong>
            </small>
        </div>
    </div>
</div>